on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: CICD

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::591309224693:role/github_actions
          aws-region: us-east-1
          role-session-name: GithubActionDeployment

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: nginx-hello-world
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        id: install

      - name: Update kube config
        run: aws eks update-kubeconfig --name eks-cluster

      - name: Deploy nodejs helm chart to EKS
        run: |
          helm install hello-world ./helm
